version: '3.9'

services:
  app:
    container_name: keyphrase_curation.core.app
    restart: unless-stopped
    image: keyphrase_curation-image
    networks:
      arg-map-br:
        ipv4_address: ${APP_DOCKER_IP}
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 /app/run.py
    volumes:
      - .:/app
      - ${PROJECT_PATH}/dataset:/dataset
    ports:
      - '${APP_LOCAL_PORT}:3132'
    env_file:
      - .docker.env

networks:
  arg-map-br:
    name: "keyphrase-curation-br"
    driver: bridge
    attachable: true
    driver_opts:
      com.docker.network.bridge.name: keyphrase-curation-br
      com.docker.network.bridge.enable_ip_masquerade: "${DOCKER_ENABLE_MASQUERADE}"
    ipam:
     config:
       - subnet: ${DOCKER_SUBNET}
         gateway: ${DOCKER_GATEWAY}