#!/bin/bash

wait_for_process() {
    local process_name="$1"
    local timeout_seconds="$2"

    start_time=$(date +%s)
    elapsed_time=0

    echo -n "Waiting for Uvicorn for $timeout_seconds seconds to start."

    while true; do
        echo -n '.'
        if ps aux | grep -v grep | grep "$process_name" &> /dev/null; then
            echo "Uvicorn successfully started"
            break
        fi

        current_time=$(date +%s)
        elapsed_time=$((current_time - start_time))

        if [ $elapsed_time -ge $timeout_seconds ]; then
            echo "Timed out. The proccess '$process_name' not started."
            break
        fi

        sleep 1
    done
}

prefix=`pwd`

SCRIPT_PID=$(pgrep -f "$prefix/run.py")
UVICORN_PID=$(pgrep -f "$prefix/venv/bin/uvicorn")

if [ "$SCRIPT_PID" != "" ]; then
    echo "Run script is already running with PID $SCRIPT_PID. Stop it first."
    exit 1
fi

if [ "$UVICORN_PID" != "" ]; then
    echo "Uvicorn is already running with PID $UVICORN_PID. Stop it first."
    exit 1
fi

nohup python3 $prefix/run.py > run.log &

wait_for_process "$prefix/venv/bin/uvicorn" "10"

./status
