#!/bin/bash

prefix=`pwd`
SCRIPT_PID=$(pgrep -f "$prefix/run.py")

if [ "$SCRIPT_PID" != "" ]; then
    echo "[RUNNING] Run script PID: $SCRIPT_PID"
else
    echo "[STOPPED] Run script not running"
fi
UVICORN_PID=$(pgrep -f "$prefix/venv/bin/uvicorn")

if [ "$UVICORN_PID" != "" ]; then
    echo "[RUNNING] Uvicorn PID: $UVICORN_PID"
else
    echo "[STOPPED] Uvicorn not running"
fi
